export const HOME = "/"
export const ACCOUNT = "/account"
export const EDIT_ACCOUNT = "/edit_account"
export const PROFILE = "/profiles/:id"
export const EVENT = "/events/:id"
export const LOGIN = "/login"
export const SIGNUP = "/sign_up"